Multicluster: Uninstall multicluster without Linkerd control plane (#5744)
Problem

If the main Linkerd control plane has been uninstalled, it is no longer possible to uninstall the multicluster extension.

```
$ bin/linkerd mc uninstall | k delete -f -
Error: you need Linkerd to be installed in order to install multicluster addons
Usage:
  linkerd multicluster uninstall [flags]
```
Solution

Fetch resources with the label `linkerd.io/extension: linkerd-multicluster` and delete them

Closes #5624

Signed-off-by: Piyush Singariya <piyushsingariya@gmail.com>