Fix recommended value formatting for '--set clusterNetworks' (#7456)
The solution `linkerd check` suggests for setting a correct
`clusterNetworks` value does not work when there are more than
one podCIDR. Here's an example recommendation by that command:

```
× cluster networks contains all node podCIDRs
    node has podCIDR(s) [242.3.68.0/25 242.3.68.128/25 242.3.66.0/25 242.3.67.128/25 242.3.69.0/25 242.3.66.128/25 242.3.64.128/25 242.3.65.128/25 242.3.67.0/25 242.3.65.0/25 242.3.64.0/25] which are not contained in the Linkerd clusterNetworks.
	Try installing linkerd via --set clusterNetworks=242.3.68.0/25,242.3.68.128/25,242.3.66.0/25,242.3.67.128/25,242.3.69.0/25,242.3.66.128/25,242.3.64.128/25,242.3.65.128/25,242.3.67.0/25,242.3.65.0/25,242.3.64.0/25
    see https://linkerd.io/2.11/checks/#l5d-cluster-networks-cidr for hints
```

If you follow that suggestion and run

```
linkerd install --set clusterNetworks=242.3.68.0/25,242.3.68.128/25,242.3.66.0/25,242.3.67.128/25,242.3.69.0/25,242.3.66.128/25,242.3.64.128/25,242.3.65.128/25,242.3.67.0/25,242.3.65.0/25,242.3.64.0/25
```

you will get the following error:

```
Error: failed parsing --set data: key "128/25" has no value (cannot end with ,)
```

Once merged, this change will make sure the list of recommended podCIDRS
are separated with escaped comma (i.e `\,`) and enclosed with `"`.

Signed-off-by: Elvin Efendi <elvin.efendiyev@gmail.com>