Remove namespace from multicluster charts (#6665)
Another part of #6584, branched off of #6635 (alpeb/no-ns-helm-core).

Stop rendering the namespace in the `linkerd-multicluster` chart as we
did in #6635.

Also:
- Got rid of the `namespace` values.yaml entry in the
  `linkerd-multicluster` and `linkerd-multicluster-link` charts, and
  also the `installNamespace` entry in the former.
- Added a dependency on the `partials` chart to the
  `linkerd-multicluster-link` chart, so that we can tap on the
  `partials.namespace` helper.
- Added the post-install hook resources to the `linkerd-multicluster`
  chart.
- We don't have any more the restriction on having the muticluster
  objects live in a separate namespace than linkerd. It's still good
  practice, and that's the default for the CLI install, but I removed
  that validation.

Finally, as a side-effect, the `allow` subcommand was fixed; it has been
broken for a while apparently:

```console
$ linkerd mc allow --service-account-name foobar
Error: template: linkerd-multicluster/templates/remote-access-service-mirror-rbac.yaml:16:7: executing "linkerd-multicluster/templates/remote-access-service-mirror-rbac.yaml" at <include "partials.annotations.created-by" $>: error calling include: template: no template "partials.annotations.created-by" associated with template "gotpl"
```