Fix dual-stack integration test (#12946)
The test was sporadically failing with
```
=== RUN   TestDualStack/Hit_IPv4_addr_directly
    dualstack_test.go:129: expected 'IPv4', received ''
--- FAIL: TestDualStack (18.09s)
```
The problem was the ipfamilies-server pod was taking longer to become ready
than the client pod, and so the request was failing. I added a readiness
probe to the server manifest so `checkPods()` blocks until all is ready.