New mc test run after `RepairEndpoints`; refactored SS tests
- Removed the `multicluster/target-statefulset` suite, and instead created the nginx SS as part of the `target1` suite. Then moved the tests for checking the nginx connections into the `target2` suite.
- Added two `linkerd mc check` tests in the `source` suite, the second triggered a minute after the first, in order to test things out after the `RepairEndoints` function has been triggered. Currently this uncovers the problem pointed out at #7733, and fails with the following output:

```console
Test script: [source] Params: []
--- FAIL: TestCheckAfterRepairEndpoints (87.71s)
    source_test.go:143: 'linkerd multicluster check' command failed
        linkerd-multicluster
        --------------------
        √ Link CRD exists
        √ Link resources are valid
                * target
        √ remote cluster access credentials are valid
                * target
        √ clusters share trust anchors
                * target
        √ service mirror controller has required permissions
                * target
        √ service mirror controllers are running
                * target
        √ all gateway mirrors are healthy
                * target
        × all mirror services have endpoints
            Some mirror services do not have endpoints:
            nginx-statefulset-0-target.multicluster-statefulset mirrored from cluster [target]
            see https://linkerd.io/2/checks/#l5d-multicluster-services-endpoints for hints
        √ all mirror services are part of a Link
        √ multicluster extension proxies are healthy
        ‼ multicluster extension proxies are up-to-date
            some proxies are not running the current version:
                * linkerd-gateway-d688dc747-x7ntn (dev-40bfe07b-alpeb)
                * linkerd-service-mirror-target-66dbf889b5-nkqkw (dev-40bfe07b-alpeb)
            see https://linkerd.io/2/checks/#l5d-multicluster-proxy-cp-version for hints
        √ multicluster extension proxies and cli versions match

        Status check results are ×

FAIL
FAIL    github.com/linkerd/linkerd2/test/integration/multicluster/source        101.101s
FAIL
```

- Also `TestMulticlusterCheck()` in `install_test.go` got a condition removed that is no longer necessary.

This should only be merged after incorporating the fix from #7733